services:
  login-service:
    build:
      context: ./backend/login
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - sql:/data
    networks:
      - Transcendance
      
  register-service:
    build:
      context: ./backend/register
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - sql:/data
    networks:
      - Transcendance

  email-service:
    build:
      context: ./backend/user-management/change-email
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - sql:/data
    networks:
      - Transcendance
    
  pass-service:
    build:
      context: ./backend/user-management/change-pass
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - sql:/data
    networks:
      - Transcendance
  
  user-service:
    build:
      context: ./backend/user-management/change-user
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - sql:/data
    networks:
      - Transcendance
  
  avatar-service:
    build:
      context: ./backend/user-management/add-avatar
      dockerfile: Dockerfile
    ports:
      - 8086:8086
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - sql:/data
    networks:
      - Transcendance

  add-friends-service:
    build:
      context: ./backend/user-management/add-friends
      dockerfile: Dockerfile
    ports:
      - 8088:8088
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - sql:/data
    networks:
      - Transcendance

  profile-info-service:
    build:
      context: ./backend/user-management/profile-info
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - sql:/data
    networks:
      - Transcendance

  pong-server:
    build:
      context: ./backend/games/pong
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    environment:
      - NODE_ENV=production
    volumes:
      - sql:/data
    networks:
      - Transcendance
    restart: unless-stopped

  games-player:
    build:
      context: ./backend/games/player
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    environment:
      - NODE_ENV=production
    volumes:
      - sql:/data
    networks:
      - Transcendance
    restart: unless-stopped

  status-service:
    build:
      context: ./backend/user-management/status
      dockerfile: Dockerfile
    ports:
      - "8094:8094"
    environment:
      - NODE_ENV=production
    volumes:
      - sql:/data
    networks:
      - Transcendance

<<<<<<< HEAD
  rooms-service:
    build:
      context: ./backend/games/rooms
      dockerfile: Dockerfile
    ports:
      - "8096:8096"
=======
  google-auth-service:
    build:
      context: ./backend/google-auth
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
>>>>>>> 99c95092daf01ed6b656c5e6640d9c0982bbb479
    environment:
      - NODE_ENV=production
    volumes:
      - sql:/data
    networks:
      - Transcendance

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8443:8443
    # volumes:
    # ./frontend/public:/usr/src/app/frontend/public
    # - public-volume:/usr/src/app
    environment:
      - NODE_ENV=production
    depends_on:
      - register-service
      - login-service
      - email-service
      - pass-service
      - add-friends-service
      - games-player
      - status-service
    networks:
      - Transcendance

  db:
    build:
      context: ./SQL
      dockerfile: Dockerfile
    volumes:
      - sql:/data
    networks:
      - Transcendance
  
  2fa:
    build:
      context: ./backend/2FA/
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    depends_on:
      - db
    volumes:
      - 2fa:/2fa
      - sql:/data
    networks:
      - Transcendance

  # prometheus:
  #   build:
  #     context: ./monitoring/prometheus
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - Transcendance

  # grafana:
  #   build:
  #     context: ./monitoring/grafana
  #     dockerfile: Dockerfile
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - Transcendance

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6380"
    networks:
      - Transcendance

networks:
  Transcendance:
    driver: bridge

volumes:
  node-modules-front:
  node-modules-back:
  node-volume:
  grafana-data:
  public-volume:
  2fa:
  sql:
  register-data:
