version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"  # Mappe le port 3000 du conteneur au port 3000 de l'hôte
    volumes:
      - .:/usr/src/app  # Monte le dossier local dans le conteneur pour un développement facile
    environment:
      - NODE_ENV=production
