version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  #Port utilise 
    volumes:
      - node-volume:/usr/src/app/backend/ #Creer le volume pour node
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - frontend
    networks:
      - Transcendance
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8443:8443
    volumes:
      - public-volume:/usr/src/app/frontend/public #Creer le volume pour js
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - Transcendance
    




networks:
  Transcendance:
    driver: bridge

volumes:
  public-volume:
  node-volume:
