services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080  #Port utilise 
    volumes:
      - node-volume:/usr/src/app/backend/ #Creer le volume pour node
      - sql:/data
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - Transcendance

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8443:8443
    volumes:
      - ./frontend/public:/usr/src/app/frontend/public
      #- public-volume:/usr/src/app/frontend/public
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - Transcendance
  
  db:
    build:
      context: ./SQL
      dockerfile: Dockerfile
    volumes:
      - sql:/data
    
    networks:
      - Transcendance
    


networks:
  Transcendance:
    driver: bridge

volumes:
  node-modules-front:
  node-modules-back:
  node-volume:
  #public-volume:
  sql:
