services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080  #Port utilise 
    volumes:
      - ./backend/:/usr/src/app/backend/ #Creer le volume pour node
      - sql:/data
      - node-modules-back:/usr/src/app/backend/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - Transcendance

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8443:8443
    volumes:
      - ./frontend/public:/usr/src/app/frontend/public
      - node-modules-front:/usr/src/app/frontend/public/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - Transcendance
  
  db:
    build:
      context: ./SQL
      dockerfile: Dockerfile
    volumes:
      - sql:/data
    
    networks:
      - Transcendance
    


networks:
  Transcendance:
    driver: bridge

volumes:
  node-modules-front:
  node-modules-back:
  sql:
