FROM grafana/grafana:latest

# (Optionnel) Ajout de plugins
# RUN grafana-cli plugins install grafana-piechart-panel

# Provisioning automatique des datasources et dashboards
COPY provisioning /etc/grafana/provisioning

