import './nav';
import './signup';
import './pongballeffects';
import './log';
import './avatarSelector';
import './style/input.css';
import './logout';
import './dataUrltoFile';
import './profile';
import './editprofile';
import './friends';
import './2FA';
import './status';
import './showToast';
import './google';
import './authCallback';
import './i18n';
import './loadPlayerData';
import './selectGame';
import './games/tournament';

console.log('Frontend chargé avec Vite + TypeScript ✅');
